export interface Testimonial {
  id: string
  name: string
  role: string
  company: string
  rating: number
  feedback: string
  avatar?: string
}

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Tamas Herold',
    role: 'Client',
    company: 'Hungary',
    rating: 5,
    feedback: 'Absolutely outstanding work! The project was exceptionally well-executed, thoroughly researched, and delivered even earlier than expected. AlphaGrid followed every instruction perfectly and went above and beyond to improve the clarity and flow of the content. Communication was smooth, professional, and excellent.',
  },
  {
    id: '2',
    name: 'Sarah Nichola',
    role: 'Client',
    company: 'India',
    rating: 5,
    feedback: 'I was on a very tight deadline and it was delivered super quick and the project was done very well. I thank AlphaGrid for their proactiveness and quick response. Thank you very much. And I will definitely get in touch for other GIS projects!',
  },
  {
    id: '3',
    name: 'Jahanus',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'AlphaGrid is an expert and professional engineer. I worked with them 2 times and now want to order another project. They are awesome!',
  },
  {
    id: '4',
    name: 'Simone Ansley',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'EXCELLENT. Everything was excellent. On time, Perfect, Polite, and the product was PERFECT. Highly, highly, highly recommend, and I am extremely picky!!',
  },
  {
    id: '5',
    name: 'Damkube',
    role: 'Client',
    company: 'Canada',
    rating: 5,
    feedback: 'Great quality, lovely to work with.',
  },
  {
    id: '6',
    name: 'Gil',
    role: 'Client',
    company: 'France',
    rating: 5,
    feedback: 'La livraison fut parfaite et les discussions intéressantes. (The delivery was perfect and the discussions were interesting.)',
  },
  {
    id: '7',
    name: 'Lalin',
    role: 'Client',
    company: 'United Kingdom',
    rating: 5,
    feedback: 'Good services.',
  },
  {
    id: '8',
    name: 'Jahanus',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'AlphaGrid is the best and professional engineer.',
  },
  {
    id: '9',
    name: 'Jahanus',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'The best of my experience.',
  },
  {
    id: '10',
    name: 'Hayk Sa',
    role: 'Client',
    company: 'Sweden',
    rating: 5,
    feedback: 'Everything was great and beyond my expectations! The communication was fast, friendly, and very professional. Highly recommend!',
  },
  {
    id: '11',
    name: 'Roxo',
    role: 'Client',
    company: 'Indonesia',
    rating: 5,
    feedback: 'Amazing, fast, exceptional!',
  },
  {
    id: '12',
    name: 'Nijadeh',
    role: 'Client',
    company: 'Kuwait',
    rating: 5,
    feedback: 'Very good work, thank you so much!',
  },
  {
    id: '13',
    name: 'Luis Winston',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'Highly recommend AlphaGrid! Delivered very good outputs and beyond my expectations. We will definitely order again!',
  },
  {
    id: '14',
    name: 'Bret Davis',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'Highly recommend AlphaGrid! Delivered a high-quality map with great accuracy and fast turnaround. Will definitely order again!',
  },
  {
    id: '15',
    name: 'Hhaykal',
    role: 'Client',
    company: 'United Arab Emirates',
    rating: 5,
    feedback: 'Working with AlphaGrid was extremely skillful. They understood the scope required perfectly, and their deliverable was professional and beyond our expectation.',
  },
  {
    id: '16',
    name: 'Patrick Southal',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'AlphaGrid transformed our project into a stunning result. Their work was incredibly detailed, allowing us to visualize every element before implementation. The design was both functional and aesthetically pleasing. Their professionalism and timely delivery made the entire process seamless. Highly recommended!',
  },
  {
    id: '17',
    name: 'Bintasan',
    role: 'Client',
    company: 'Malaysia',
    rating: 5,
    feedback: 'AlphaGrid provided detailed work as requested. Very professional with their work and really polite in discussing the job that I had posted.',
  },
  {
    id: '18',
    name: 'Hhaykal',
    role: 'Client',
    company: 'United Arab Emirates',
    rating: 5,
    feedback: 'The team is very professional and the deliverables are well detailed and comply with the requirement.',
  },
  {
    id: '19',
    name: 'Antonia Vicentes',
    role: 'Client',
    company: 'Spain',
    rating: 5,
    feedback: 'Very good work, very professional and fast. I will trust them with future projects.',
  },
  {
    id: '20',
    name: 'Akshay Verma',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'Nice work! Will do it again.',
  },
  {
    id: '21',
    name: 'Nathan Clark',
    role: 'Client',
    company: 'Canada',
    rating: 5,
    feedback: 'AlphaGrid did an outstanding job with my GIS mapping request. They were professional, communicative, and delivered exactly what I expected. Highly recommended.',
  },
  {
    id: '22',
    name: 'Christ Sameul',
    role: 'Client',
    company: 'Portugal',
    rating: 5,
    feedback: 'I am really impressed with their work! They were quick and very professional. Highly recommend. Thank you!',
  },
  {
    id: '23',
    name: 'Limpu',
    role: 'Client',
    company: 'Spain',
    rating: 5,
    feedback: 'I recommend AlphaGrid\'s services.',
  },
  {
    id: '24',
    name: 'Limpu',
    role: 'Client',
    company: 'Spain',
    rating: 5,
    feedback: 'Very professional and very good at doing the work.',
  },
  {
    id: '25',
    name: 'Srishti Sharma',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'Very happy with the result. Keep it up. Definitely do more projects with you. Thank you.',
  },
  {
    id: '26',
    name: 'Erroral Robert',
    role: 'Client',
    company: 'United Kingdom',
    rating: 5,
    feedback: 'This is the second time I have worked with AlphaGrid and the output was perfect and exceeded my expectations. AlphaGrid is highly professional, skilled, and easy to communicate with. I will definitely reach out again for future projects. I highly recommend them for any professional GIS and Remote Sensing work.',
  },
  {
    id: '27',
    name: 'Erroral Robert',
    role: 'Client',
    company: 'United Kingdom',
    rating: 5,
    feedback: 'I am very happy with the results, fast delivery, clear communication, and precise work. AlphaGrid created a highly attractive and comprehensive map that significantly enhanced the value of my report. Excellent work! Highly recommended for high-quality results.',
  },
  {
    id: '28',
    name: 'Rukshan',
    role: 'Client',
    company: 'Australia',
    rating: 5,
    feedback: 'This is the second time we have hired AlphaGrid, and once again, the results were outstanding. They are highly skilled, very easy to work with, and communicate effectively. Thank you for your exceptional work.',
  },
  {
    id: '29',
    name: 'Alvin Rhodes',
    role: 'Client',
    company: 'United States',
    rating: 5,
    feedback: 'Perfect and fast delivery. The output is beyond expectations. Easy to communicate and AlphaGrid is a true expert in the GIS field. No doubt!',
  },
  {
    id: '30',
    name: 'Rukshan',
    role: 'Client',
    company: 'Australia',
    rating: 5,
    feedback: 'Great service! Fast delivery and understood the exact requirement with just a brief discussion. I will definitely use this service again. Thanks!',
  },
]


